services:
  - type: web
    name: airtable-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AIRTABLE_CLIENT_ID
        sync: false
      - key: AIRTABLE_CLIENT_SECRET
        sync: false
      - key: AIRTABLE_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
